version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
      
    
  front:
    build: ./client
    ports:
      - 3000:3000
    working_dir: /app

  back:
    build: ./server
    ports:
      - 8000:8000
    working_dir: /app

volumes:
  mongodata: