export const FETCH_TOURMATES_SUCCESS = "FETCH_TOURMATES_SUCCESS";
export const FETCH_TOURMATE_SUCCESS = "FETCH_TOURMATE_SUCCESS";

export const GET_DIRECTIONS_SUCCESS = "GET_DIRECTIONS";
export const GET_DIRECTION_SUCCESS = "GET_DIRECTION";
